### ISSUE TITLE
[bug] when you click it too fast

### ISSUE THREAD

**Issue by zzz6519003** [bokuweb/react-motion-menu#16]
:beer:

**Comment by bokuweb** [comment]
Thunks!
Does it mean, you want to slow down the operation when click ?

**Comment by zzz6519003** [comment]
when you click it too fast, you will see there's an icon not disappearing()

**Comment by bokuweb** [comment]
Thunks! I see. I will research and correct

**Comment by zzz6519003** [comment]
:beer: 
thanks, great work!

**Comment by bokuweb** [comment]
Fixed!! thunks!!
