### ISSUE TITLE
[install error] ➜  react-motion-menu git:(zzz-dev) ✗ npm run-script watch:example  > react-motion-menu@0.1.4 watch:example /Users/zhengzhongzhao/Develop/reacts/react-motion-menu > watchify --extension=js -o example/dist/bundle.js example/src/index.js  Error: Cannot find module '../../lib' from '/Users/zhengzhongzhao/Develop/reacts/react-motion-menu/example/src' Error: Cannot find module '../../lib' from '/Users/zhengzhongzhao/Develop/reacts/react-motion-menu/example/src'

### ISSUE THREAD

**Issue by zzz6519003** [bokuweb/react-motion-menu#17]
➜  react-motion-menu git:(zzz-dev) ✗ npm run-script watch:example

> react-motion-menu@0.1.4 watch:example /Users/zhengzhongzhao/Develop/reacts/react-motion-menu
> watchify --extension=js -o example/dist/bundle.js example/src/index.js

Error: Cannot find module '../../lib' from '/Users/zhengzhongzhao/Develop/reacts/react-motion-menu/example/src'
Error: Cannot find module '../../lib' from '/Users/zhengzhongzhao/Develop/reacts/react-motion-menu/example/src'

:beer:

**Comment by bokuweb** [comment]
Thanks!
But, I'm not able to reproduce.
What is your npm version?

**Comment by zzz6519003** [comment]
i fix it by modify 'lib' to 'src' XD
